"""TFCE: agreement with PALM, and the properties that follow from the formula.

The first and most important test compares this implementation against the
real ``palm_tfce.m``.  PALM's output was generated by running that MATLAB
function in Octave over four meshes -- different sizes, masked and unmasked,
and three settings of ``H``/``E`` -- and the results are stored verbatim in
``tests/data/palm_tfce_reference.npz``.  Nothing here re-derives what PALM
should have produced; the numbers in that file *are* PALM's, printed at full
double precision, and agreement is asserted at 1e-12 relative, which is a
loose bound on the 1e-15 the two actually achieve.

The rest of the file checks the things the integral

    TFCE(v) = ∫ e(h)^E · h^H dh

implies exactly, so that a future change that still matched PALM's four
reference maps by luck would not also survive these: how the score scales with
the map, with the areas, and with each exponent; that the mask and the mesh's
connectivity are respected; and that a map with nothing above zero scores zero.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest
from scipy.sparse import csr_matrix

from cifti_state.stats.tfce import (
    PALM_2D,
    PALM_DEFAULT,
    TFCEEngine,
    TFCESettings,
    tfce,
)

REFERENCE = Path(__file__).parent / "data" / "palm_tfce_reference.npz"


# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #


def adjacency_from_faces(faces: np.ndarray, n: int) -> csr_matrix:
    """The edge graph of a triangulation, symmetric and unweighted."""
    f = np.asarray(faces)
    a = np.concatenate([f[:, 0], f[:, 0], f[:, 1], f[:, 1], f[:, 2], f[:, 2]])
    b = np.concatenate([f[:, 1], f[:, 2], f[:, 0], f[:, 2], f[:, 0], f[:, 1]])
    m = csr_matrix((np.ones(a.size, np.int8), (a, b)), shape=(n, n))
    m.data[:] = 1
    return m


def chain(n: int) -> csr_matrix:
    """A path graph: vertex i touches i-1 and i+1, and nothing else."""
    rows = list(range(n - 1)) + list(range(1, n))
    cols = list(range(1, n)) + list(range(n - 1))
    return csr_matrix((np.ones(len(rows)), (rows, cols)), shape=(n, n))


@pytest.fixture(scope="module")
def palm_cases():
    """PALM's own output for four meshes, as generated by palm_tfce.m."""
    if not REFERENCE.exists():          # pragma: no cover - fixture is committed
        pytest.skip("the PALM reference file is not present")
    return np.load(REFERENCE, allow_pickle=False)


# --------------------------------------------------------------------------- #
# agreement with PALM
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize("tag", ["c1", "c2", "c3", "c6"])
def test_matches_palm_to_machine_precision(palm_cases, tag):
    """The reference implementation, vertex for vertex."""
    height, extent, dh, n_vertices = palm_cases[f"{tag}/params"]
    n_vertices = int(n_vertices)
    mask = palm_cases[f"{tag}/mask"]
    values = np.zeros(n_vertices)
    values[mask] = palm_cases[f"{tag}/values"]

    mine = tfce(
        values,
        adjacency_from_faces(palm_cases[f"{tag}/faces"], n_vertices),
        palm_cases[f"{tag}/area"],
        mask=mask,
        settings=TFCESettings(height=height, extent=extent, dh=dh),
    )[mask]

    reference = palm_cases[f"{tag}/palm"]
    relative = np.abs(mine - reference) / np.maximum(np.abs(reference), 1e-30)
    assert relative.max() < 1e-12


def test_the_reference_cases_actually_exercise_different_settings(palm_cases):
    """A guard on the fixture: four identical cases would prove very little."""
    settings = {tuple(palm_cases[f"{tag}/params"][:2]) for tag in
                ("c1", "c2", "c3", "c6")}
    assert len(settings) == 3                       # (2, .5), (2, 1), (3, .25)
    assert not palm_cases["c2/mask"].all()          # one case is masked


# --------------------------------------------------------------------------- #
# the properties the integral implies
# --------------------------------------------------------------------------- #


def test_a_map_with_nothing_positive_scores_zero():
    """No height is above any step, so PALM's loop body never runs."""
    graph = chain(20)
    area = np.ones(20)
    assert not np.any(tfce(-np.arange(1.0, 21.0), graph, area))
    assert not np.any(tfce(np.zeros(20), graph, area))


def test_scaling_the_map_scales_the_score_by_c_to_the_H_plus_one():
    """With the automatic ladder the steps scale with the map, so ``c^(H+1)``.

    ``h^H`` contributes ``c^H`` and the ``dh`` the integral is multiplied by
    contributes another factor of ``c``.  The extent never changes, because
    scaling a map cannot change which vertices are above a proportionally
    scaled threshold -- which is exactly why the automatic ladder makes the
    score comparable across permutations of wildly different magnitude.
    """
    rng = np.random.default_rng(3)
    values = np.abs(rng.normal(size=200))
    graph, area = chain(200), np.ones(200)
    for height in (1.0, 2.0, 3.0):
        settings = TFCESettings(height=height, extent=0.5)
        base = tfce(values, graph, area, settings=settings)
        scaled = tfce(7.0 * values, graph, area, settings=settings)
        assert np.allclose(scaled, 7.0 ** (height + 1.0) * base, rtol=1e-10)


def test_scaling_the_areas_scales_the_score_by_c_to_the_E():
    """Extent enters only as ``e(h)^E``, and area is what extent means here."""
    rng = np.random.default_rng(4)
    values = np.abs(rng.normal(size=150))
    graph = chain(150)
    for extent in (0.25, 0.5, 1.0):
        settings = TFCESettings(extent=extent)
        base = tfce(values, graph, np.ones(150), settings=settings)
        bigger = tfce(values, graph, np.full(150, 3.0), settings=settings)
        assert np.allclose(bigger, 3.0 ** extent * base, rtol=1e-10)


def test_extent_is_area_and_not_a_vertex_count():
    """Two clusters of equal area score alike however finely each is cut.

    On a real surface the tessellation is uneven, so a vertex count would hand
    an advantage to whichever region happens to be sampled more densely.  Here
    one blob is four vertices of area 1 and the other is eight of area 0.5.
    """
    graph = chain(40)
    area = np.ones(40)
    area[20:28] = 0.5
    values = np.zeros(40)
    values[4:8] = 2.0                    # 4 vertices x 1.0  = 4 mm²
    values[20:28] = 2.0                  # 8 vertices x 0.5  = 4 mm²

    scores = tfce(values, graph, area)
    assert scores[4:8].max() == pytest.approx(scores[20:28].max(), rel=1e-12)


def test_the_mask_removes_a_vertex_from_the_cluster_it_would_have_joined():
    """A masked vertex scores zero *and* stops the cluster passing through it."""
    graph = chain(30)
    area = np.ones(30)
    values = np.zeros(30)
    values[10:21] = 3.0                  # eleven vertices, 15 in the middle

    mask = np.ones(30, dtype=bool)
    mask[15] = False                     # cut the run in half
    scores = tfce(values, graph, area, mask=mask)

    assert scores[15] == 0.0
    whole = tfce(values, graph, area)
    # Half the extent, so a smaller score for every surviving member.
    assert np.all(scores[10:15] < whole[10:15])
    # Five vertices either side of the cut, and the two halves score alike.
    assert scores[10] == pytest.approx(scores[20], rel=1e-12)
    assert scores[10] == pytest.approx(scores[16], rel=1e-12)


def test_clusters_do_not_leap_a_gap_in_the_graph():
    """Connectivity comes from the mesh, not from the vertex numbering."""
    n = 40
    left, right = chain(20), chain(20)
    from scipy.sparse import block_diag

    graph = csr_matrix(block_diag((left, right), format="csr"))
    values = np.zeros(n)
    values[18:22] = 2.0                  # 18,19 in one block; 20,21 in the other
    scores = tfce(values, graph, np.ones(n))

    joined = tfce(values, chain(n), np.ones(n))     # the same run, now connected
    assert np.all(scores[18:22] < joined[18:22])


def test_a_larger_extent_exponent_favours_the_broad_bump_over_the_spike():
    """The point of E: it is the dial between focal and diffuse effects."""
    n = 300
    graph, area = chain(n), np.ones(n)
    values = np.zeros(n)
    values[50] = 6.0                                  # a tall, narrow spike
    values[150:190] = 3.0                             # a broad, lower bump

    focal = tfce(values, graph, area, settings=TFCESettings(extent=0.1))
    diffuse = tfce(values, graph, area, settings=PALM_2D)   # E = 1
    assert focal[50] > focal[150:190].max()
    assert diffuse[150:190].max() > diffuse[50]


def test_a_taller_height_exponent_favours_the_spike_over_the_bump():
    """And H is the same dial turned the other way."""
    n = 300
    graph, area = chain(n), np.ones(n)
    values = np.zeros(n)
    values[50] = 6.0
    values[150:190] = 3.0

    flat = tfce(values, graph, area, settings=TFCESettings(height=0.5, extent=1.0))
    steep = tfce(values, graph, area, settings=TFCESettings(height=6.0, extent=1.0))
    assert flat[150:190].max() > flat[50]
    assert steep[50] > steep[150:190].max()


def test_a_fixed_step_reproduces_the_automatic_one_when_it_is_the_same_step():
    """The two ladder branches are one ladder, built two ways.

    PALM's own surface branch cannot run with a fixed ``dh`` -- it never
    assigns the variable it multiplies by -- so this is the only handle there
    is on that path: set the fixed step to what the automatic one would have
    chosen, and the two must agree.
    """
    rng = np.random.default_rng(31)
    values = np.abs(rng.normal(size=180))
    graph, area = chain(180), np.ones(180)

    automatic = tfce(values, graph, area, settings=TFCESettings(steps=100))
    fixed = tfce(values, graph, area,
                 settings=TFCESettings(dh=values.max() / 100))
    assert np.allclose(automatic, fixed, rtol=1e-9)

    # And a coarser fixed step really is coarser, rather than being ignored.
    coarse = tfce(values, graph, area, settings=TFCESettings(dh=values.max() / 5))
    assert not np.allclose(automatic, coarse, rtol=1e-3)


def test_more_steps_converge_on_the_integral():
    """The ladder is a quadrature, so refining it should stop changing much."""
    rng = np.random.default_rng(11)
    values = np.abs(rng.normal(size=250))
    graph, area = chain(250), np.ones(250)

    coarse = tfce(values, graph, area, settings=TFCESettings(steps=100))
    fine = tfce(values, graph, area, settings=TFCESettings(steps=400))
    finer = tfce(values, graph, area, settings=TFCESettings(steps=1600))

    assert np.abs(fine - finer).max() < np.abs(coarse - fine).max()
    assert np.abs(fine - finer).max() / finer.max() < 0.01


# --------------------------------------------------------------------------- #
# the engine
# --------------------------------------------------------------------------- #


def test_the_engine_and_the_one_shot_agree_and_the_engine_is_reusable():
    """Reusing an engine must not let one map's state leak into the next."""
    rng = np.random.default_rng(7)
    graph, area = chain(120), rng.uniform(0.5, 2.0, size=120)
    engine = TFCEEngine(graph, area, settings=PALM_DEFAULT)

    maps = [np.abs(rng.normal(size=120)) for _ in range(4)]
    first = [engine(m) for m in maps]
    again = [engine(m) for m in reversed(maps)][::-1]     # a different order

    for m, once, twice in zip(maps, first, again):
        assert np.array_equal(once, twice)
        assert np.allclose(once, tfce(m, graph, area), rtol=0, atol=0)


def test_a_mesh_and_an_area_vector_that_disagree_are_refused():
    with pytest.raises(ValueError, match="areas"):
        TFCEEngine(chain(10), np.ones(11))


def test_a_map_of_the_wrong_length_is_refused():
    engine = TFCEEngine(chain(10), np.ones(10))
    with pytest.raises(ValueError, match="vertices"):
        engine(np.ones(11))


# --------------------------------------------------------------------------- #
# inside the permutation test, which is the only place TFCE becomes inference
# --------------------------------------------------------------------------- #


def test_the_unpermuted_rearrangement_supplies_the_observed_tfce():
    """The identity leads the null, so the observed score is its first entry.

    This is the hinge the whole correction turns on: the observed map has to be
    scored by exactly the same function as every rearrangement, or the P value
    compares two different statistics.
    """
    from cifti_state.stats.glm import fit_glm
    from cifti_state.stats.permutation import permutation_test

    rng = np.random.default_rng(21)
    n = 120
    graph, area = chain(n), np.ones(n)
    data = rng.normal(size=(12, n))
    data[:, 40:60] += 1.2
    design = np.ones((12, 1))
    contrast = np.array([1.0])

    engine = TFCEEngine(graph, area, settings=PALM_DEFAULT)
    result = permutation_test(
        data, design, contrast, graph, n_permutations=64,
        cluster_forming=2.0, tfce_engine=engine, seed=0,
    )
    observed = engine(np.abs(fit_glm(data, design, contrast).t))

    assert result.max_tfce is not None
    assert result.max_tfce[0] == pytest.approx(observed.max(), rel=1e-12)
    assert result.tfce_settings == PALM_DEFAULT.to_dict()


def test_the_tfce_null_gives_p_values_between_the_resolution_and_one():
    from cifti_state.stats.glm import fit_glm
    from cifti_state.stats.permutation import permutation_test

    rng = np.random.default_rng(22)
    n = 100
    graph = chain(n)
    data = rng.normal(size=(10, n))
    data[:, 30:50] += 2.0
    design, contrast = np.ones((10, 1)), np.array([1.0])
    engine = TFCEEngine(graph, np.ones(n))
    result = permutation_test(
        data, design, contrast, graph,
        n_permutations=128, cluster_forming=2.0, tfce_engine=engine, seed=1,
    )

    observed = engine(np.abs(fit_glm(data, design, contrast).t))
    p = result.tfce_pvalue(observed)
    assert p.min() >= result.resolution() - 1e-15
    assert p.max() <= 1.0
    # A score of zero is beaten by every rearrangement.
    assert float(result.tfce_pvalue(0.0)) == pytest.approx(1.0)
    assert result.tfce_threshold(0.05) > 0
    assert "TFCE" in result.describe()


def test_asking_for_tfce_p_values_without_a_tfce_null_is_refused():
    from cifti_state.stats.permutation import permutation_test

    rng = np.random.default_rng(23)
    graph = chain(60)
    result = permutation_test(
        rng.normal(size=(8, 60)), np.ones((8, 1)), np.array([1.0]), graph,
        n_permutations=32, cluster_forming=2.0, seed=0,
    )
    assert result.max_tfce is None
    with pytest.raises(ValueError, match="did not compute TFCE"):
        result.tfce_pvalue(1.0)


def test_the_permutation_loop_is_deterministic_under_a_seed():
    from cifti_state.stats.permutation import permutation_test

    rng = np.random.default_rng(24)
    n = 80
    graph = chain(n)
    data = rng.normal(size=(9, n))
    engine = TFCEEngine(graph, np.ones(n))
    kwargs = dict(n_permutations=48, cluster_forming=2.0, tfce_engine=engine, seed=5)
    a = permutation_test(data, np.ones((9, 1)), np.array([1.0]), graph, **kwargs)
    b = permutation_test(data, np.ones((9, 1)), np.array([1.0]), graph, **kwargs)
    assert np.array_equal(a.max_tfce, b.max_tfce)


def test_the_settings_describe_themselves():
    assert "H=2" in PALM_DEFAULT.describe()
    assert "auto" in PALM_DEFAULT.describe()
    assert "E=1" in PALM_2D.describe()
    assert TFCESettings(dh=0.25).describe().endswith("0.25")
    assert PALM_DEFAULT.to_dict() == {"H": 2.0, "E": 0.5, "dh": 0.0, "steps": 100}
