"""Permutation: the null distribution built from the data instead of assumed.

Random field theory answers "how surprising is this?" from a model of the
field -- Gaussian or t, smooth, stationary enough.  Permutation answers the
same question by rearranging the data under the null hypothesis and looking at
what comes out.  It needs no distributional assumption and no smoothness
estimate, and its family-wise error control is exact by construction, at the
cost of doing the analysis a few thousand times.

The two are worth having together: when they agree you can believe the answer,
and when they disagree the RFT assumptions are where to look.

**How the null is built.** Under the null the effect of interest is absent, so
the rows of the model's *residuals* are exchangeable:

* a one-sample or paired test is symmetric about zero, so the null is generated
  by flipping the sign of each subject's map;
* a two-sample test says the group labels carry no information, so the null is
  generated by shuffling them.

With nuisance covariates in the model the naive version is wrong -- shuffling
the raw data destroys the covariate relationship too -- so this uses
Freedman-Lane: the nuisance-only model is fitted first, and it is *its*
residuals that get permuted, leaving the covariate structure intact.

**How it stays fast.** Refitting the whole model a few thousand times would be
slow, but almost none of that work is new: the design never changes, only the
row order.  Writing the permuted fit in terms of ``pinv(X)`` with its columns
permuted turns each permutation into one small matrix product, and the residual
sum of squares comes from a p x p form rather than an n x n one.  A few
thousand permutations over a whole cortical surface then cost minutes rather
than hours -- and the loop reports progress and honours a cancel token, because
it is still the slowest thing in the package.

Reference: Winkler AM, Ridgway GR, Webster MA, Smith SM, Nichols TE (2014).
*Permutation inference for the general linear model.* NeuroImage 92:381-397.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

import numpy as np
from scipy.sparse import csr_matrix
from scipy.sparse.csgraph import connected_components

from ..logging_setup import get_logger
from ..types import CancelToken, ProgressFn, check_cancelled, report_progress

log = get_logger(__name__)

__all__ = ["PermutationResult", "permutation_test", "cluster_labels"]


@dataclass
class PermutationResult:
    """Null distributions of the maximum statistic and the maximum cluster."""

    max_statistic: np.ndarray        #: (n_permutations,) max |t| or max t
    max_extent: np.ndarray           #: (n_permutations,) largest cluster, in vertices
    max_mass: np.ndarray             #: (n_permutations,) largest cluster, summed statistic
    n_permutations: int
    exhaustive: bool                 #: every possible rearrangement was used
    scheme: str                      #: sign_flip | shuffle
    direction: str
    cluster_forming: float
    extent: int
    seed: Optional[int] = None
    notes: list[str] = field(default_factory=list)
    #: (n_permutations,) max TFCE score, when TFCE was asked for.
    max_tfce: Optional[np.ndarray] = None
    tfce_settings: Optional[dict] = None

    # -- p values ----------------------------------------------------------- #

    def statistic_pvalue(self, observed) -> np.ndarray:
        """FWE-corrected P for a statistic height, by the max-statistic rule."""
        return _tail_pvalue(np.asarray(observed, dtype=float), self.max_statistic)

    def extent_pvalue(self, observed) -> np.ndarray:
        """FWE-corrected P for a cluster's extent in vertices."""
        return _tail_pvalue(np.asarray(observed, dtype=float), self.max_extent)

    def mass_pvalue(self, observed) -> np.ndarray:
        """FWE-corrected P for a cluster's mass (its summed statistic)."""
        return _tail_pvalue(np.asarray(observed, dtype=float), self.max_mass)

    def tfce_pvalue(self, observed) -> np.ndarray:
        """FWE-corrected P per vertex, from the max-TFCE null.

        TFCE scores every vertex, so this is a whole map of corrected P values
        rather than one number per cluster -- which is the point of it: no
        cluster-forming threshold had to be chosen to get here.
        """
        if self.max_tfce is None:
            raise ValueError(
                "this permutation test did not compute TFCE; pass a TFCE "
                "engine to permutation_test, or tfce=True to the group test"
            )
        return _tail_pvalue(np.asarray(observed, dtype=float), self.max_tfce)

    def tfce_threshold(self, alpha: float = 0.05) -> float:
        """The TFCE score a vertex needs to reach corrected *alpha*."""
        if self.max_tfce is None:
            raise ValueError("this permutation test did not compute TFCE")
        return float(np.quantile(self.max_tfce, 1.0 - alpha))

    # -- thresholds --------------------------------------------------------- #

    def statistic_threshold(self, alpha: float = 0.05) -> float:
        return float(np.quantile(self.max_statistic, 1.0 - alpha))

    def extent_threshold(self, alpha: float = 0.05) -> float:
        return float(np.quantile(self.max_extent, 1.0 - alpha))

    def resolution(self) -> float:
        """The smallest P value this many rearrangements can produce."""
        return 1.0 / self.n_permutations

    def describe(self) -> str:
        return (
            f"{self.n_permutations} {self.scheme} permutations"
            f"{' (exhaustive)' if self.exhaustive else ''}: "
            f"max |t| threshold {self.statistic_threshold(0.05):.3f}, "
            f"cluster extent threshold {self.extent_threshold(0.05):.0f} vertices "
            f"at u={self.cluster_forming:g}"
            + (
                f", TFCE threshold {self.tfce_threshold(0.05):.3g}"
                if self.max_tfce is not None else ""
            )
            + f"; smallest reportable P {self.resolution():.2g}"
        )

    def to_dict(self) -> dict:
        return {
            "n_permutations": int(self.n_permutations),
            "exhaustive": bool(self.exhaustive),
            "scheme": self.scheme,
            "direction": self.direction,
            "cluster_forming": float(self.cluster_forming),
            "extent": int(self.extent),
            "seed": self.seed,
            "statistic_threshold_05": self.statistic_threshold(0.05),
            "extent_threshold_05": self.extent_threshold(0.05),
            "resolution": self.resolution(),
            "tfce": None if self.max_tfce is None else {
                **(self.tfce_settings or {}),
                "threshold_05": self.tfce_threshold(0.05),
            },
        }


#: Relative slack when counting the null values that beat the observed one.
#: The observed statistic and the identity rearrangement's are the same number
#: arrived at by two routes -- the fit, and the permuted-pseudoinverse form the
#: loop uses -- so they agree only to the last few bits.  Without a little
#: slack that rounding would occasionally push the observed value past its own
#: entry in the null and produce P = 0, which no permutation test can mean.
_TIE_TOLERANCE = 1e-10


def _tail_pvalue(observed: np.ndarray, null: np.ndarray) -> np.ndarray:
    """``#{null >= observed} / n`` -- PALM's convention, and never zero.

    The unpermuted arrangement is itself one of the arrangements under the
    null, and it is the first entry of every null distribution here.  So it is
    already counted once, which is what keeps the smallest possible P value at
    ``1/n`` rather than at the impossible zero -- and it must not be counted
    *twice*, which is what the familiar ``(b+1)/(m+1)`` form would do given a
    null that already contains it.  PALM counts it once; so does this.
    """
    null = np.sort(np.asarray(null, dtype=float))
    n = null.size
    observed = np.asarray(observed, dtype=float)
    slack = np.abs(observed) * _TIE_TOLERANCE
    at_least = n - np.searchsorted(null, observed - slack, side="left")
    return at_least / n


# --------------------------------------------------------------------------- #
# clustering, stripped to what the loop needs
# --------------------------------------------------------------------------- #


def cluster_labels(
    values: np.ndarray,
    adjacency: csr_matrix,
    threshold: float,
    *,
    extent: int = 1,
    mask: Optional[np.ndarray] = None,
) -> tuple[np.ndarray, np.ndarray]:
    """Sizes and masses of the supra-threshold clusters of *values*.

    A deliberately bare version of :func:`cifti_state.core.cluster.find_clusters`:
    no labelling, no bookkeeping, no hemispheres -- it runs a few thousand
    times and only its two summary numbers are ever used.
    """
    above = values > threshold
    if mask is not None:
        above &= mask
    index = np.flatnonzero(above)
    if index.size == 0:
        return np.zeros(0), np.zeros(0)

    sub = adjacency[index][:, index]
    _, membership = connected_components(sub, directed=False)
    sizes = np.bincount(membership)
    masses = np.bincount(membership, weights=values[index])
    keep = sizes >= extent
    return sizes[keep].astype(float), masses[keep]


# --------------------------------------------------------------------------- #
# the test
# --------------------------------------------------------------------------- #


def permutation_test(
    data: np.ndarray,
    design_matrix: np.ndarray,
    contrast: np.ndarray,
    adjacency: csr_matrix,
    *,
    scheme: str = "auto",
    n_permutations: int = 5000,
    cluster_forming: float = 3.0,
    extent: int = 1,
    direction: str = "two_sided",
    mask: Optional[np.ndarray] = None,
    tfce_engine=None,
    seed: Optional[int] = 0,
    batch: int = 64,
    progress: Optional[ProgressFn] = None,
    cancel: Optional[CancelToken] = None,
) -> PermutationResult:
    """Build the null distributions of the maximum statistic and cluster.

    *adjacency* must cover the same vertices as *data*'s columns -- for a
    two-hemisphere analysis that is the block-diagonal graph of both
    hemispheres, which keeps clusters from leaping the midline.

    ``scheme="auto"`` picks sign flipping when the model is an intercept alone
    (a one-sample or paired test) and shuffling otherwise.

    Passing a :class:`~cifti_state.stats.tfce.TFCEEngine` as *tfce_engine* adds
    the max-TFCE null distribution, which is the only thing that turns a TFCE
    score into a P value.  It is by far the most expensive part of the loop, so
    it is opt-in.
    """
    y = np.asarray(data, dtype=np.float64)
    x = np.asarray(design_matrix, dtype=np.float64)
    c = np.asarray(contrast, dtype=np.float64).ravel()
    n_obs, n_vertices = y.shape

    if x.shape[0] != n_obs:
        raise ValueError("the design and the data disagree about the sample size")
    if adjacency.shape[0] != n_vertices:
        raise ValueError(
            f"the adjacency covers {adjacency.shape[0]} vertices but the data "
            f"has {n_vertices}"
        )

    nuisance = np.flatnonzero(np.abs(c) < 1e-12)
    if scheme == "auto":
        scheme = "sign_flip" if _is_intercept_only(x, c) else "shuffle"
    if scheme not in ("sign_flip", "shuffle"):
        raise ValueError(f"unknown scheme {scheme!r}")

    # Freedman-Lane: permute the residuals of the nuisance-only model, so the
    # covariate structure survives the rearrangement.
    if nuisance.size:
        z = x[:, nuisance]
        reduced_residuals = y - z @ (np.linalg.pinv(z) @ y)
        notes = [f"Freedman-Lane on {nuisance.size} nuisance predictor(s)"]
    else:
        reduced_residuals = y
        notes = []

    rank = int(np.linalg.matrix_rank(x))
    dof = float(n_obs - rank)
    pinv = np.linalg.pinv(x)                      # (p, n)
    xtx = x.T @ x                                 # (p, p)
    variance_factor = float(c @ np.linalg.pinv(xtx) @ c)
    scale = 1.0 / np.sqrt(variance_factor / dof)

    total_ss = np.einsum("ij,ij->j", reduced_residuals, reduced_residuals)

    rearrangements, exhaustive = _rearrangements(
        n_obs, scheme, n_permutations, seed,
        groups=None if scheme == "sign_flip" else _group_from_contrast(x, c),
    )
    n_permutations = len(rearrangements)
    notes.append(f"{n_permutations} rearrangements")

    vertex_mask = None if mask is None else np.asarray(mask, dtype=bool)
    absolute = direction == "two_sided"

    max_statistic = np.empty(n_permutations)
    max_extent = np.zeros(n_permutations)
    max_mass = np.zeros(n_permutations)
    max_tfce = np.zeros(n_permutations) if tfce_engine is not None else None

    log.info(
        "permutation: %s, %d rearrangements%s, u=%g, extent>=%d, %s%s",
        scheme, n_permutations, " (exhaustive)" if exhaustive else "",
        cluster_forming, extent, direction,
        f", TFCE ({tfce_engine.settings.describe()})" if tfce_engine else "",
    )

    done = 0
    for start in range(0, n_permutations, batch):
        check_cancelled(cancel)
        block = rearrangements[start:start + batch]

        # One matrix product for the whole block: pinv(X) with its columns
        # rearranged is the permuted fit, so nothing has to be refitted.
        weights = np.concatenate([_apply(pinv, r, scheme) for r in block], axis=0)
        betas = weights @ reduced_residuals          # (len(block) * p, V)
        betas = betas.reshape(len(block), x.shape[1], n_vertices)

        effect = np.einsum("p,bpv->bv", c, betas)
        explained = np.einsum("bpv,pq,bqv->bv", betas, xtx, betas)
        residual_ss = np.maximum(total_ss[None, :] - explained, 0.0)

        with np.errstate(divide="ignore", invalid="ignore"):
            t = scale * effect / np.sqrt(residual_ss)
        t[~np.isfinite(t)] = 0.0
        if vertex_mask is not None:
            t[:, ~vertex_mask] = 0.0

        for row in range(len(block)):
            values = np.abs(t[row]) if absolute else (
                -t[row] if direction == "negative" else t[row]
            )
            max_statistic[done] = values.max() if values.size else 0.0
            sizes, masses = cluster_labels(
                values, adjacency, cluster_forming,
                extent=extent, mask=vertex_mask,
            )
            max_extent[done] = sizes.max() if sizes.size else 0.0
            max_mass[done] = masses.max() if masses.size else 0.0
            if max_tfce is not None:
                # TFCE is scored on exactly the same map the other statistics
                # see -- |t| for a two-tailed test, as PALM does it.
                max_tfce[done] = tfce_engine(values).max()
            done += 1

        report_progress(
            progress, done / n_permutations,
            f"permutation {done}/{n_permutations}",
        )

    result = PermutationResult(
        max_statistic=max_statistic,
        max_extent=max_extent,
        max_mass=max_mass,
        n_permutations=n_permutations,
        exhaustive=exhaustive,
        scheme=scheme,
        direction=direction,
        cluster_forming=float(cluster_forming),
        extent=int(extent),
        seed=seed,
        notes=notes,
        max_tfce=max_tfce,
        tfce_settings=(
            tfce_engine.settings.to_dict() if tfce_engine is not None else None
        ),
    )
    log.info("permutation: %s", result.describe())
    return result


# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #


def _is_intercept_only(x: np.ndarray, c: np.ndarray) -> bool:
    """Is the tested predictor a column of ones, with nothing else tested?"""
    tested = np.flatnonzero(np.abs(c) > 1e-12)
    if tested.size != 1:
        return False
    column = x[:, tested[0]]
    return bool(np.allclose(column, column[0]) and column[0] != 0)


def _group_from_contrast(x: np.ndarray, c: np.ndarray) -> Optional[np.ndarray]:
    """The two-level predictor being tested, if that is what it is."""
    tested = np.flatnonzero(np.abs(c) > 1e-12)
    if tested.size != 1:
        return None
    column = x[:, tested[0]]
    levels = np.unique(column)
    if levels.size == 2:
        return (column == levels[1]).astype(int)
    return None


def _apply(pinv: np.ndarray, rearrangement: np.ndarray, scheme: str) -> np.ndarray:
    """``pinv(X)`` with its columns permuted, or their signs flipped."""
    if scheme == "sign_flip":
        return pinv * rearrangement[None, :]
    return pinv[:, rearrangement]


def _rearrangements(
    n: int, scheme: str, requested: int, seed: Optional[int],
    *, groups: Optional[np.ndarray] = None,
) -> tuple[list[np.ndarray], bool]:
    """The rearrangements to use, with the identity always first.

    When the number of distinct rearrangements is smaller than the number
    requested, all of them are used and the test becomes exact rather than
    approximate -- and that is reported, because it changes how the smallest
    possible P value should be read.
    """
    rng = np.random.default_rng(seed)

    if scheme == "sign_flip":
        total = 2 ** n
        if total <= requested:
            signs = [
                np.array([1.0 if not (i >> bit) & 1 else -1.0 for bit in range(n)])
                for i in range(total)
            ]
            return signs, True
        out = [np.ones(n)]
        seen = {out[0].tobytes()}
        while len(out) < requested:
            candidate = rng.choice([-1.0, 1.0], size=n)
            key = candidate.tobytes()
            if key in seen:
                continue
            seen.add(key)
            out.append(candidate)
        return out, False

    identity = np.arange(n)

    # With a two-group design only the split matters, and there are C(n, n1) of
    # them. When that is fewer than asked for, enumerate the lot: the test is
    # then exact rather than approximate.
    if groups is not None:
        from itertools import combinations
        from math import comb

        labels = np.asarray(groups)
        positions = np.flatnonzero(labels == 1)
        total = comb(n, positions.size)
        if total <= max(requested, 1):
            out = []
            for chosen in combinations(range(n), positions.size):
                order = np.empty(n, dtype=int)
                mask = np.zeros(n, dtype=bool)
                mask[list(chosen)] = True
                order[mask] = positions
                order[~mask] = np.flatnonzero(labels == 0)
                out.append(order)
            # Put the identity first so the observed arrangement leads.
            for index, order in enumerate(out):
                if np.array_equal(labels[order], labels):
                    out[0], out[index] = out[index], out[0]
                    break
            return out, True

    out = [identity]
    seen = {identity.tobytes()}
    attempts = 0
    limit = requested * 20
    while len(out) < requested and attempts < limit:
        attempts += 1
        candidate = rng.permutation(n)
        # Two permutations that produce the same group split give the same
        # statistic, so keep only distinct splits when there is a grouping.
        key = (
            candidate.tobytes() if groups is None
            else np.asarray(groups)[candidate].tobytes()
        )
        if key in seen:
            continue
        seen.add(key)
        out.append(candidate)
    return out, False
